name: Test Security Tools container build

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
  pull_request:
    branches:
      - main
    paths:
      - Dockerfile

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build container
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: theredguild/container-sec-tools:latest