name: Test Container Sec Tools

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and test all tools
        run: |
          for tool in $(make list | tail -n +2); do
            echo "Testing tool: $tool"
            make test $tool
          done
